default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mt_takao_development


test:
  <<: *default
  database: mt_takao_test

production:
  <<: *default
  database: mt_takao_production
  username: mt_takao
  password: <%= ENV['TAKAO_DATABASE_PASSWORD'] %>
